
// This file has been generated by the GUI designer. Do not modify.
namespace Match3
{
	public partial class GameWindow
	{
		private global::Gtk.VBox vbox;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label_time;

		private global::Gtk.Label label_score;

		private global::Gtk.DrawingArea drawingarea;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Match3.GameWindow
			this.WidthRequest = 605;
			this.HeightRequest = 620;
			this.Name = "Match3.GameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Match3");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child Match3.GameWindow.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox();
			this.vbox.Name = "vbox";
			this.vbox.BorderWidth = ((uint)(5));
			// Container child vbox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label_time = new global::Gtk.Label();
			this.label_time.Name = "label_time";
			this.label_time.LabelProp = global::Mono.Unix.Catalog.GetString("Time: ");
			this.hbox1.Add(this.label_time);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label_time]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label_score = new global::Gtk.Label();
			this.label_score.Name = "label_score";
			this.label_score.LabelProp = global::Mono.Unix.Catalog.GetString("Score: ");
			this.hbox1.Add(this.label_score);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label_score]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.drawingarea = new global::Gtk.DrawingArea();
			this.drawingarea.WidthRequest = 600;
			this.drawingarea.HeightRequest = 600;
			this.drawingarea.Name = "drawingarea";
			this.vbox.Add(this.drawingarea);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox[this.drawingarea]));
			w4.Position = 1;
			this.Add(this.vbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 605;
			this.DefaultHeight = 620;
			this.Show();
			this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingareaExposeEvent);
		}
	}
}
